### PR TITLE
Actions in WebApp

### PR DESCRIPTION
**Pull request by termoshtt**
Add some contents in the pages for run.
I will implement some actions argued in #180, #181.

### CODE REVIEW

**Comment by termoshtt** [comment]
Add delete project action

**Comment by xeno1991** [comment]
LGTM

僕の環境だとsequenceがディレクトリの下に入ってるので見れない(´・ω・｀)

**Comment by termoshtt** [comment]
Fileの属性を推定した

**Comment by xeno1991** [comment]
LGTM

**Pull request merged**
